export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'

export const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST'
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS'
export const GET_TAGS_FAIL = 'GET_TAGS_FAIL'

export const ADD_TO_COMPARE_REQUEST = 'ADD_TO_COMPARE_REQUEST'
export const ADD_TO_COMPARE_SUCCESS = 'ADD_TO_COMPARE_SUCCESS'
export const ADD_TO_COMPARE_FAIL = 'ADD_TO_COMPARE_FAIL'

export const REMOVE_FROM_COMPARE_REQUEST = 'REMOVE_FROM_COMPARE_REQUEST'
export const REMOVE_FROM_COMPARE_SUCCESS = 'REMOVE_FROM_COMPARE_SUCCESS'
export const REMOVE_FROM_COMPARE_FAIL = 'REMOVE_FROM_COMPARE_FAIL'