
export const GET_CART_REQUEST = 'GET_CART_REQUEST'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_FAIL = 'GET_CART_FAIL'

export const ADD_CART_REQUEST = 'ADD_CART_REQUEST'
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS'
export const ADD_CART_FAIL = 'ADD_CART_FAIL'

export const DELETE_CART_REQUEST = 'DELETE_CART_REQUEST'
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS'
export const DELETE_CART_FAIL = 'DELETE_CART_FAIL'

export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS'

export const GET_WISHLIST_REQUEST = 'GET_WISHLIST_REQUEST'
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS'
export const GET_WISHLIST_FAIL = 'GET_WISHLIST_FAIL'

export const ADD_WISHLIST_REQUEST = 'ADD_WISHLIST_REQUEST'
export const ADD_WISHLIST_SUCCESS = 'ADD_WISHLIST_SUCCESS'
export const ADD_WISHLIST_FAIL = 'ADD_WISHLIST_FAIL'

export const DELETE_WISHLIST_REQUEST = 'DELETE_WISHLIST_REQUEST'
export const DELETE_WISHLIST_SUCCESS = 'DELETE_WISHLIST_SUCCESS'
export const DELETE_WISHLIST_FAIL = 'DELETE_WISHLIST_FAIL'

export const ORDER_PROGRESS_REQUEST = 'ORDER_PROGRESS_REQUEST'
export const ORDER_PROGRESS_SUCCESS = 'ORDER_PROGRESS_SUCCESS'
export const ORDER_PROGRESS_FAIL = 'ORDER_PROGRESS_FAIL'