export const GET_GENERAL_REQUEST = 'GET_GENERAL_REQUEST'
export const GET_GENERAL_SUCCESS = 'GET_GENERAL_SUCCESS'
export const GET_GENERAL_FAIL = 'GET_GENERAL_FAIL'

export const GET_LOGO_REQUEST = 'GET_LOGO_REQUEST'
export const GET_LOGO_SUCCESS = 'GET_LOGO_SUCCESS'
export const GET_LOGO_FAIL = 'GET_LOGO_FAIL'

export const GET_MENUS_REQUEST = 'GET_MENUS_REQUEST'
export const GET_MENUS_SUCCESS = 'GET_MENUS_SUCCESS'
export const GET_MENUS_FAIL = 'GET_MENUS_FAIL'

export const GET_FOOTER_REQUEST = 'GET_FOOTER_REQUEST'
export const GET_FOOTER_SUCCESS = 'GET_FOOTER_SUCCESS'
export const GET_FOOTER_FAIL = 'GET_FOOTER_FAIL'

export const GET_NEWSLETTER_REQUEST = 'GET_NEWSLETTER_REQUEST'
export const GET_NEWSLETTER_SUCCESS = 'GET_NEWSLETTER_SUCCESS'
export const GET_NEWSLETTER_FAIL = 'GET_NEWSLETTER_FAIL'

export const GET_FEATURES_REQUEST = 'GET_FEATURES_REQUEST'
export const GET_FEATURES_SUCCESS = 'GET_FEATURES_SUCCESS'
export const GET_FEATURES_FAIL = 'GET_FEATURES_FAIL'

export const GET_PRODUCT_PAGE_REQUEST = 'GET_PRODUCT_PAGE_REQUEST'
export const GET_PRODUCT_PAGE_SUCCESS = 'GET_PRODUCT_PAGE_SUCCESS'
export const GET_PRODUCT_PAGE_FAIL = 'GET_PRODUCT_PAGE_FAIL'

export const GET_FEATURED_CATEGORIES_REQUEST = 'GET_FEATURED_CATEGORIES_REQUEST'
export const GET_FEATURED_CATEGORIES_SUCCESS = 'GET_FEATURED_CATEGORIES_SUCCESS'
export const GET_FEATURED_CATEGORIES_FAIL = 'GET_FEATURED_CATEGORIES_FAIL'

export const GET_TOP_BRANDS_REQUEST = 'GET_TOP_BRANDS_REQUEST'
export const GET_TOP_BRANDS_SUCCESS = 'GET_TOP_BRANDS_SUCCESS'
export const GET_TOP_BRANDS_FAIL = 'GET_TOP_BRANDS_FAIL'

export const GET_PRODUCT_TABS_REQUEST = 'GET_PRODUCT_TABS_REQUEST'
export const GET_PRODUCT_TABS_SUCCESS = 'GET_PRODUCT_TABS_SUCCESS'
export const GET_PRODUCT_TABS_FAIL = 'GET_PRODUCT_TABS_FAIL'

// export const GET_SLIDER_BANNERS_REQUEST = 'GET_PRODUCT_DETAILS_REQUEST'
// export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS'
// export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL'

// export const GET_THREE_COLUMN_FULL_WIDTH_BANNES_REQUEST = 'GET_PRODUCT_DETAILS_REQUEST'
// export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS'
// export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL'

// export const GET_TWO_COLUMN_BANNERS_REQUEST = 'GET_PRODUCT_DETAILS_REQUEST'
// export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS'
// export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL'

// export const GET_THREE_COLUMN_BANNERS_REQUEST = 'GET_PRODUCT_DETAILS_REQUEST'
// export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS'
// export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL'

// export const GET_ONE_COLUMN_BANNER_REQUEST = 'GET_PRODUCT_DETAILS_REQUEST'
// export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS'
// export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL'