
export const GET_LOGIN_REQUEST = 'GET_LOGIN_REQUEST'
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS'
export const GET_LOGIN_FAIL = 'GET_LOGIN_FAIL'

export const GET_LOGOUT_REQUEST = 'GET_LOGOUT_REQUEST'
export const GET_LOGOUT_SUCCESS = 'GET_LOGOUT_SUCCESS'
export const GET_LOGOUT_FAIL = 'GET_LOGOUT_FAIL'

export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST'
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS'
export const GET_USER_DETAILS_FAIL = 'GET_USER_DETAILS_FAIL'

export const REMOVE_USER_DETAILS_SUCCESS = 'REMOVE_USER_DETAILS_SUCCESS'

// export const GET_REGISTER_REQUEST = 'GET_REGISTER_REQUEST'
// export const GET_REGISTER_SUCCESS = 'GET_REGISTER_SUCCESS'
// export const GET_REGISTER_FAIL = 'GET_REGISTER_FAIL'